server:
  port: 9201
service-url:
  user-service: http://localhost:8206

spring:
  application:
    name: apigateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
    gateway:
      routes:
        - id: path_route #路由的ID
          uri: ${service-url.user-service}/u/user/{id} #匹配后路由地址
          predicates: # 断言，路径相匹配的进行路由
            - Path=/u/user/{id}