server:
  port: 8210
spring:
  application:
    name: nacos-ribbon-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #≈‰÷√Nacosµÿ÷∑
management:
      endpoints:
        web:
          exposure:
            include: '*'

