server:
  port: 8206
spring:
  application:
    name: consul-user-service
  cloud:
    consul:
      host: 192.168.3.3
      port: 8500
      discovery:
        service-name: ${spring.application.name}
