server:
  port: 8401
spring:
  application:
    name: sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.137.1:8848
    sentinel:
      transport:
        dashboard: 192.168.137.1:8080
        port: 8719
      datasource:
        ds1:
          nacos:
            server-addr:  localhost:8848
            dataId: sentinel-service
            group: DEFAULT_GROUP
            data-type: json
            rule-type: flow
service-url:
  user-service: http://nacos-user-service
management:
  endpoints:
    web:
      exposure:
        include: '*'
